apiVersion: v1
kind: Pod
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  containers:
  - name: chirpstack-simulator
    image: prrsjunior/chirpstack-simulator:dev
    command: ["/chirpstack-simulator/build/chirpstack-simulator"]
    args: ["-c", "/config/chirpstack-simulator.toml"]
#    command: ["/bin/sh"]
#    args: ["-c", "while true; do echo hello; sleep 1000000;done"]
    volumeMounts:
    - mountPath: /config
      name: config-simulator
  volumes:
    - name: config-simulator
      configMap:
        name: app-config
        items:
        - key: config
          path: chirpstack-simulator.toml
