kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresinit-pv-volume
  labels:
    type: local
    app: postgresinit
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/guru/chirpstack/chirpstack-docker/configuration/postgresql/initdb"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresinit-pv-claim
  labels:
    app: postgresinit
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mosquitto-pv-volume
  labels:
    type: local
    app: mosquitto
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/guru/chirpstack/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto
  labels:
    app: mosquitto	
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

